name: CI Tests

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "src/**"
      - "api/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  quality-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --dev

      - name: isort
        run: uv run isort src/ api/ tests/ --check-only

      - name: black
        run: uv run black src/ api/ tests/ --check

      - name: pylint
        run: uv run pylint src/ api/ tests/ --recursive=y -rn -sn

      - name: Unit tests
        run: uv run pytest tests/unit/ -v
